### ISSUE TITLE
Use some form of SemVer

### ISSUE THREAD

**Issue by RivenSkaye** [Niklas20114552/deezium#2]
The current (listed as alpha) release is tagged `1.0`, which could give off the wrong idea for repository maintainers and packagers, as well as the less attentive user.
The [Semantic Versioning Specification (SemVer)](https://semver.org/) exists to convey state of development and whether or not changes can be considered breaking.

Different projects and ecosystems use different exact implementations, for example Rust's semver has some notable differences from the spec, whereas Python tries to stick closer to it, and NPM has its own implementation too. But it would be helpful to convey the current project state a little clearer for future tags and releases I think. Which for this project would mean 0.x.y versioning until a first "stable" release

**Comment by tabbeddev** [comment]
Thank you.  
I have changed the current version tag and will follow this for future releases.
